### ISSUE TITLE
TypeError: GraphqlSubscriptionConsumer() takes no arguments

### ISSUE THREAD

**Issue by singlerider** [shreyas44/graphene-subscriptions#7]
Continuing the conversation from https://github.com/jaydenwindle/graphene-subscriptions/pull/25:

I was able to build your repository from git using. I'll be using this non-production repository and branch for illustration:

https://github.com/singlerider/telemetry_gatherer/tree/graphene-subscriptions

The README details how to run the project. After it launches, you'll see the following error:

```
WebSocket HANDSHAKING /graphql/ [172.17.0.1:50120]
Exception inside application: GraphqlSubscriptionConsumer() takes no arguments
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/daphne/cli.py", line 30, in asgi
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/channels/routing.py", line 57, in __call__
    return await application(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/channels/routing.py", line 57, in __call__
    return await application(scope, receive, send)
  File "/usr/local/lib/python3.8/site-packages/channels/routing.py", line 136, in __call__
    return await application(
  File "/usr/local/lib/python3.8/site-packages/asgiref/compatibility.py", line 33, in new_application
    instance = application(scope)
TypeError: GraphqlSubscriptionConsumer() takes no arguments
WebSocket DISCONNECT /graphql/ [172.17.0.1:50120]
```

I've tried in Python 3.8 and 3.9 so far.

**Comment by shreyas44** [comment]
@singlerider Have you tried running it outside the Docker container, maybe in a virtualenv? 

Also, I noticed you're getting Django channels from source.

https://github.com/singlerider/telemetry_gatherer/blob/3b80198e8097c3ac2575202785124809209dcea9/requirements.txt#L8

Is there a reason for that?

**Comment by singlerider** [comment]
I use PyEnv and can replicate any version really easily and yes, I tested outside of Docker with `3.8.3` and `3.9.0`.

The reason why I'm using Channels from source is because if I install from PyPi, it doesn't support ASGI 3.

Which is why I was asking earlier if you have a working sample project with a good `requirements.txt`.

**Comment by shreyas44** [comment]
> I use PyEnv and can replicate any version really easily and yes, I tested outside of Docker with `3.8.3` and `3.9.0`.
> 
> The reason why I'm using Channels from source is because if I install from PyPi, it doesn't support ASGI 3.
> 
> Which is why I was asking earlier if you have a working sample project with a good `requirements.txt`.

@singlerider in the app I used this for i just have `channels==2.4.0` in the `requirements.txt`.

**Comment by shreyas44** [comment]
I just noticed there's a problem with your project structure (not sure if this was intentional or a mistake)
`cockpit/telemetry` a `django app` should be in `./telemetry`

**Comment by singlerider** [comment]
Which versions of Python, Django, Django-Graphene, and ASGIRef?

**Comment by shreyas44** [comment]
> Which versions of Python, Django, Django-Graphene, and ASGIRef?

```
Python 3.8.1

asgiref==3.2.7
Django==3.0.5
graphene==2.1.8
graphene-django==2.10.1
```

**Comment by shreyas44** [comment]
asdfasd

**Comment by singlerider** [comment]
I updated this to revert to old versions of those packages and now I'm back to the old Django Channels error (when I view GraphIQL at /graphql):

```
/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/home/MYUSERNAME/.pyenv/versions/VIRTUALENV/lib/python3.8/site-packages/daphne/http_protocol.py", line 163, in process
    self.application_queue = yield maybeDeferred(
TypeError: __call__() missing 2 required positional arguments: 'receive' and 'send'
```

This took me back to where I was before.

Is there anything glaring here? Why would it work in another project and not this one?

https://github.com/singlerider/telemetry_gatherer/tree/graphene-subscriptions/cockpit

**Comment by shreyas44** [comment]
@singlerider check out the main branch in https://github.com/shreyas44/telemetry_gatherer and let me know if it works.

**Comment by singlerider** [comment]
@shreyas44 it works great! I'll study the changes that I notice, isolate them, and open a corresponding PR upstream (or here) to get the instructions updated. Thanks a ton for helping investigate.

**Comment by shreyas44** [comment]
@singlerider No problem! Also, check out the https://github.com/shreyas44/graphene-subscriptions/pull/4. It creates an easy way to create subscriptions and removes a lot of the manual work you have to currently do. It's not completely documented but feel free to raise an issue :)
